spring:
  application:
    name: "sach"
  config:
    import: "configserver:http://localhost:8071"
  cloud:
    config:
      name: sach, common
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              ReactiveMongoTemplate: DEBUG